name: flutter_app_market
description: Android应用跳转到手机的各大应用市场，Google、华为、小米、oppo、vivo、应用宝等各大主流的应用市场.
version: 1.1.0
homepage: https://github.com/chentl666/flutter_app_market

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.tianle.flutter_app_market
        pluginClass: FlutterAppMarketPlugin
      ios:
        pluginClass: FlutterAppMarketPlugin
